---
sudo: required
language: python
cache: pip
services:
  - docker
jobs:
  fast_finish: true
  include:
    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - ANSIBLE=2.5
    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - ANSIBLE=2.6
    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - ANSIBLE=2.7
    - os: linux
      env:
        - ANSIBLE=2.5
install:
  - pip install tox-travis git-semver
script:
  - tox
deploy:
  provider: script
  skip_cleanup: true
  script:
    - git --version
    - .travis/releaser.sh
  on:
    branch: master
branches:
  only:
    - master
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
